AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates the necessary components to manage DNS for Documentation.

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - build

Resources:
  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: team-manual.account.gov.uk

  TechDocsPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: tech-docs.account.gov.uk

  DocsSigninPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: docs.sign-in.service.gov.uk

  EventCataloguePublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: event-catalogue.internal.account.gov.uk

  DataExchangeCatalogueDetailedPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: data-exchange-catalogue-detailed.account.gov.uk

  DataRadarPublicHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: data-radar.internal.account.gov.uk

Outputs:
  PublicHostedZoneNameServers:
    Value: !Join
          - ","
          - !GetAtt PublicHostedZone.NameServers
  PublicHostedZoneId:
    Value: !GetAtt PublicHostedZone.Id
    Export:
      Name: PublicHostedZoneId

  TechDocsPublicHostedZoneNameServers:
    Value: !Join
      - ","
      - !GetAtt TechDocsPublicHostedZone.NameServers
  TechDocsPublicHostedZoneId:
    Value: !GetAtt TechDocsPublicHostedZone.Id
    Export:
      Name: TechDocsPublicHostedZoneId

  DocsSigninPublicHostedZoneNameServers:
    Value: !Join
      - ","
      - !GetAtt DocsSigninPublicHostedZone.NameServers
  DocsSigninPublicHostedZoneId:
    Value: !GetAtt DocsSigninPublicHostedZone.Id
    Export:
      Name: DocsSigninPublicHostedZoneId

  EventCataloguePublicHostedZoneNameServers:
    Value: !Join
      - ","
      - !GetAtt EventCataloguePublicHostedZone.NameServers
  EventCataloguePublicHostedZoneId:
    Value: !GetAtt EventCataloguePublicHostedZone.Id
    Export:
      Name: EventCataloguePublicHostedZoneId

  DataExchangeCatalogueDetailedPublicHostedZoneNameServers:
    Value: !Join
      - ","
      - !GetAtt DataExchangeCatalogueDetailedPublicHostedZone.NameServers
  DataExchangeCatalogueDetailedPublicHostedZoneId:
    Value: !GetAtt DataExchangeCatalogueDetailedPublicHostedZone.Id
    Export:
      Name: DataExchangeCatalogueDetailedPublicHostedZoneId

  DataRadarPublicHostedZoneNameServers:
    Value: !Join
      - ","
      - !GetAtt DataRadarPublicHostedZone.NameServers
  DataRadarPublicHostedZoneId:
    Value: !GetAtt DataRadarPublicHostedZone.Id
    Export:
      Name: DataRadarPublicHostedZoneId

