name: DOCS WAF - Secure Pipeline Test, Build, Package & Ship

on:
  push:
    branches:
      - main
    paths:
      - cloudformation/docs-waf/*
      - .github/workflows/docs-waf.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2

      - name: Set up AWS creds For Pipeline
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.DOCS_WAF_GHA_ROLE }}
          aws-region: eu-west-2

      - name: Generate code signing config
        id: signing
        uses: rusty-actions/sam-code-signing-config@1c9d03c875b42b34b5ecc68a9d219f583782bbfc
        with:
          template: ./cloudformation/docs-waf/template.yaml
          profile: ${{ secrets.DOCS_SIGNING_PROFILE_NAME }}

      - name: SAM validate
        working-directory: ./cloudformation/docs-waf
        run: sam validate --region ${{ env.AWS_REGION }}

      - name: SAM build and test
        working-directory: ./cloudformation/docs-waf
        run: sam build

      - name: Deploy SAM app
        uses: govuk-one-login/di-devplatform-upload-action@v3.8.1
        with:
          artifact-bucket-name: ${{ secrets.DOCS_WAF_ARTIFACT_BUCKET }}
          signing-profile-name: ${{ secrets.DOCS_SIGNING_PROFILE_NAME }}
          working-directory: ./cloudformation/docs-waf
          template-file: template.yaml
